repos:
  - repo: local
    hooks:
      - id: poetry-check
        name: Poetry Environment Check
        entry: bash -c 'if [ -z "$GITHUB_ACTIONS" ]; then poetry install && poetry run pip list | grep -q django || (echo "Django not found in Poetry environment. Run poetry install." && exit 1); fi'
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
        additional_dependencies: [flake8-django]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=120"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-django
        args: ["--reformat", "--max-line-length=120"]
        files: '\.(html|djhtml)$'

  - repo: local
    hooks:
      - id: django-collectstatic
        name: Django Collect Static
        entry: bash -c 'if [ -z "$GITHUB_ACTIONS" ]; then cd "$(git rev-parse --show-toplevel)" && poetry run python manage.py collectstatic --noinput; fi'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        verbose: true
      - id: django-test
        name: Django Tests
        entry: bash -c 'if [ -z "$GITHUB_ACTIONS" ]; then cd "$(git rev-parse --show-toplevel)" && poetry run python manage.py test --failfast; fi'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        verbose: true

fail_fast: true
