---
- name: Install certbot and nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Check if SSL certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: ssl_cert_exists
  when: domain_name is defined

- name: Obtain SSL certificate with certbot
  command: >
    certbot --nginx -d {{ domain_name }}
    --non-interactive --agree-tos
    --email admin@{{ domain_name }}
    --redirect
  when: 
    - domain_name is defined
    - not ssl_cert_exists.stat.exists
  notify: restart nginx

- name: Set up automatic certificate renewal
  cron:
    name: "Renew SSL certificates"
    minute: "0"
    hour: "2"
    job: "/usr/bin/certbot renew --quiet && systemctl reload nginx"
    user: root
  when: domain_name is defined

- name: Test certificate renewal
  command: certbot renew --dry-run
  when: 
    - domain_name is defined
    - ssl_cert_exists.stat.exists
  changed_when: false 