---
all:
  vars:
    # Project configuration
    project_name: education-website
    project_user: "{{ ansible_user }}"
    project_path: "/home/{{ project_user }}/{{ project_name }}"
    python_version: "3.11"
    app_port: 8000
    
    # Django configuration
    django_settings_module: "web.settings"
    django_secret_key: "{{ vault_django_secret_key }}"
    django_debug: false
    
    # Database configuration
    db_engine: postgresql
    db_name: "{{ project_name | replace('-', '_') }}"
    db_user: "{{ project_user }}"
    db_password: "{{ vault_db_password }}"
    db_host: localhost
    db_port: 5432
    
    # SSL and domain configuration
    enable_ssl: true
    enable_https_redirect: true
    
    # Application configuration
    gunicorn_workers: 4
    gunicorn_worker_class: "uvicorn.workers.UvicornWorker"
    
    # External services
    stripe_publishable_key: "{{ vault_stripe_publishable_key | default('') }}"
    stripe_secret_key: "{{ vault_stripe_secret_key | default('') }}"
    stripe_webhook_secret: "{{ vault_stripe_webhook_secret | default('') }}"
    sendgrid_api_key: "{{ vault_sendgrid_api_key | default('') }}"
    slack_webhook_url: "{{ vault_slack_webhook_url | default('') }}"
    
    # Global variables for all environments
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    development:
      hosts:
        test-server:
          ansible_host: 45.76.4.171
          ansible_user: root
          ansible_ssh_pass: "Jm-7Yt?(,KLQ!r$Q"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          domain_name: "{{ vault_dev_domain_name }}"
          server_role: development
      vars:
        # Development environment settings
        debug_mode: true
        enable_ssl: false
        enable_https_redirect: false
        
    staging:
      hosts:
        # Add staging servers here when needed
      vars:
        # Staging environment settings
        debug_mode: false
        enable_ssl: true
        enable_https_redirect: true
        
    production:
      hosts:
        # Add production servers here when needed
      vars:
        # Production environment settings
        debug_mode: false
        enable_ssl: true
        enable_https_redirect: true