# Generated by Django 5.1.6 on 2025-03-21 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="challengesubmission",
            unique_together={("user", "challenge")},
        ),
    ]
