# Generated by Django 5.1.6 on 2025-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_goods_alter_cartitem_unique_together_cartitem_goods_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("link", models.URLField()),
            ],
        ),
    ]
