# Generated by Django 5.1.6 on 2025-03-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_livechallenge_livechallengesubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livechallengesubmission',
            name='submission_text',
        ),
        migrations.CreateModel(
            name='LiveChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('live_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='web.livechallenge')),
            ],
        ),
        migrations.CreateModel(
            name='LiveChallengeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='web.livechallengequestion')),
            ],
        ),
        migrations.CreateModel(
            name='LiveChallengeSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.livechallengequestion')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.livechallengeoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='web.livechallengesubmission')),
            ],
        ),
    ]
