# Generated by Django 5.1.6 on 2025-03-17 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_donation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_name", models.CharField(help_text="Name of the completed course", max_length=200)),
                (
                    "certificate_file",
                    models.FileField(help_text="Generated certificate file", upload_to="certificates/"),
                ),
                ("date_issued", models.DateField(auto_now_add=True, help_text="Date when the certificate was issued")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who completed the course",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
