# Generated by Django 5.1.6 on 2025-03-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_livechallengesubmission_submission_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechallengesubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
