# Generated by Django 5.1.6 on 2025-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_quiz_quizquestion_quizoption_quizsubmission"),
        ("web", "0024_create_success_story"),
    ]

    operations = []
