# Generated by Django 5.1.6 on 2025-03-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_create_success_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("link", models.URLField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("virtual", "Virtual"), ("in_person", "In Person")], default="virtual", max_length=10
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("online", "Online"), ("in_person", "In Person")], default="online", max_length=10
                    ),
                ),
            ],
        ),
    ]
