# Generated by Django 5.1.6 on 2025-03-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_certificate"),
        ("web", "0024_create_success_story"),
    ]

    operations = []
