# Generated by Django 5.1.6 on 2025-03-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_create_success_story'),
        ('web', '0024_merge_20250317_2010'),
    ]

    operations = [
    ]
