# Generated by Django 5.1.6 on 2025-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_meetup"),
        ("web", "0024_create_success_story"),
    ]

    operations = []
