# Generated by Django 5.1.6 on 2025-03-17 23:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_merge_0024_certificate_0024_create_success_story"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="certificate_file",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="date_issued",
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="completion_date",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificate",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="web.course",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="certificates", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
