# Generated by Django 5.1.6 on 2025-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_merge_0023_meetup_0024_create_success_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="event_type",
            field=models.CharField(
                choices=[("online", "Online"), ("in_person", "In Person")], default="online", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="meetup",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meetup",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="meetup",
            name="type",
            field=models.CharField(
                choices=[("virtual", "Virtual"), ("in_person", "In Person")], default="virtual", max_length=10
            ),
        ),
    ]
