# Generated by Django 5.1.6 on 2025-03-18 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_merge_20250318_0729"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizsubmission",
            unique_together={("user", "quiz")},
        ),
    ]
