# Generated by Django 5.1.6 on 2025-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_session_latitude_session_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teaching_style",
            field=models.CharField(
                choices=[("lecture", "Lecture"), ("interactive", "Interactive"), ("self-paced", "Self-paced")],
                default="lecture",
                help_text="The primary teaching style for this course",
                max_length=20,
            ),
        ),
    ]
