# Generated by Django 5.1.6 on 2025-03-18 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_alter_quizsubmission_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizoption",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="quizquestion",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="quizoption",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="duration_minutes",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name="QuizAnswerSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.quizquestion")),
                (
                    "selected_option",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.quizoption"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="web.quizsubmission"
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "question")},
            },
        ),
    ]
