# Generated by Django 5.1.6 on 2025-03-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_challenge_type_and_week_number_updates"),
        ("web", "0027_educationalvideo"),
    ]

    operations = []
