# Generated by Django 5.1.6 on 2025-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username_is_public",
            field=models.BooleanField(
                default=False, 
                help_text="Allow your username to appear on public leaderboards",
                db_index=True,
                verbose_name="Username Public Visibility"
            ),
        ),
    ]
