# Generated by Django 5.1.6 on 2025-03-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0027_alter_quizoption_options_alter_quizquestion_options_and_more"),
        ("web", "0028_certificate"),
    ]

    operations = []
