# Generated by Django 5.1.6 on 2025-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teaching_style",
            field=models.CharField(
                choices=[("lecture", "Lecture"), ("interactive", "Interactive"), ("self-paced", "Self-paced")],
                default="lecture",
                help_text="The primary teaching style for this course",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Latitude coordinate for mapping", max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Longitude coordinate for mapping", max_digits=9, null=True
            ),
        ),
    ]
