# Generated by Django 5.1.6 on 2025-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_certificate"),
        ("web", "0028_merge_20250319_1822"),
    ]

    operations = []
