# Generated by Django 5.1.6 on 2025-03-19 13:11

"""
This migration removes the "username_is_public" field as part of the profile achievements tracking feature.
"""


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_add_username_is_public_to_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username_is_public",
        ),
    ]
