# Generated by Django 5.1.6 on 2025-03-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_challenge_challenge_type_alter_challenge_week_number_and_more"),
        ("web", "0029_learningstreak"),
    ]

    operations = []
