# Generated by Django 5.1.6 on 2025-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_merge_20250319_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="points",
            field=models.PositiveIntegerField(default=10, help_text="Points awarded for a correct answer"),
        ),
    ]
