# Generated by Django 5.1.6 on 2025-03-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_merge_20250320_0718"),
        ("web", "0030_quiz_quizquestion_quizoption_userquiz"),
    ]

    operations = []
