# Generated by Django 5.1.6 on 2025-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_quiz_quizquestion_quizoption_userquiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Latitude coordinate for mapping", max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Longitude coordinate for mapping", max_digits=9, null=True
            ),
        ),
    ]
