# Generated by Django 5.1.6 on 2025-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_remove_profile_username_is_public"),
    ]

    operations = [
        migrations.AddField(
          model_name="profile",
          name="achievements",
          field=models.PositiveIntegerField(default=0, help_text="Number of achievements earned by the user."),
        ),
        migrations.AddField(
            model_name="profile",
            name="username_is_public",
            field=models.BooleanField(default=False, help_text="Indicates if the user's username is publicly visible."),
        ),
    ]
