# Generated by Django 5.1.6 on 2025-03-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_achievement_badge_icon_and_more"),
        ("web", "0031_session_latitude_session_longitude"),
    ]

    operations = []
