# Generated by Django 5.1.6 on 2025-03-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_rename_completion_date_teamgoalmember_completed_at_and_more"),
        ("web", "0032_session_latitude_session_longitude"),
    ]

    operations = []
