# Generated by Django 5.1.6 on 2025-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_rename_completion_date_teamgoalmember_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
    ]
