# Generated by Django 5.1.6 on 2025-03-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_rename_completion_date_teamgoalmember_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTBadge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "blockchain",
                    models.CharField(
                        choices=[("ethereum", "Ethereum"), ("polygon", "Polygon"), ("solana", "Solana")],
                        default="polygon",
                        max_length=20,
                    ),
                ),
                ("token_id", models.CharField(blank=True, max_length=100)),
                ("contract_address", models.CharField(blank=True, max_length=100)),
                ("transaction_hash", models.CharField(blank=True, max_length=100)),
                ("metadata_uri", models.URLField(blank=True)),
                ("minted_at", models.DateTimeField(blank=True)),
                ("wallet_address", models.CharField(blank=True, max_length=100)),
                (
                    "achievement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nft_badge", to="web.achievement"
                    ),
                ),
            ],
        ),
    ]
