# Generated by Django 5.1.6 on 2025-03-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_merge_20250320_1701"),
        ("web", "0032_rename_completion_date_teamgoalmember_completed_at_and_more"),
    ]

    operations = []
