# Generated by Django 5.1.6 on 2025-03-22 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_rename_completion_date_teamgoalmember_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeableLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("pr", "Pull Request"),
                            ("article", "Article"),
                            ("website", "Website"),
                            ("project", "Project"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkGrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=2,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[("weekly", "Weekly Challenge"), ("one_time", "One-time Challenge")],
                default="weekly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="week_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("challenge_type", "weekly")),
                fields=("week_number",),
                name="unique_week_number_for_weekly_challenges",
            ),
        ),
        migrations.AddField(
            model_name="gradeablelink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="submitted_links", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="linkgrade",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="grades", to="web.gradeablelink"
            ),
        ),
        migrations.AddField(
            model_name="linkgrade",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="given_grades", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="linkgrade",
            unique_together={("link", "user")},
        ),
    ]
