# Generated by Django 5.1.6 on 2025-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_rename_achievements_profile_overall_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="overall_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username_is_public",
            field=models.BooleanField(default=False),
        ),
    ]
