# Generated by Django 5.1.6 on 2025-03-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_challengesubmission_points_awarded_and_more"),
        ("web", "0036_peerchallenge_peerchallengeinvitation"),
    ]

    operations = []
