# Generated by Django 5.1.6 on 2025-03-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_profile_how_did_you_hear_about_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Latitude coordinate for mapping", max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Longitude coordinate for mapping", max_digits=9, null=True
            ),
        ),
    ]
