# Generated by Django 5.1.6 on 2025-03-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_challengesubmission_points_awarded_and_more"),
        ("web", "0037_profile_how_did_you_hear_about_us"),
    ]

    operations = []
