# Generated by Django 5.1.6 on 2025-03-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_merge_20250323_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="points",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
