# Generated by Django 5.1.6 on 2025-03-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_waitingroom_fulfilled_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="peermessage",
            name="encrypted_key",
            field=models.TextField(blank=True, default=""),
        ),
    ]
