# Generated by Django 5.1.6 on 2025-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_waitingroom_fulfilled_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengesubmission",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
