# Generated by Django 5.1.6 on 2025-03-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_waitingroom_fulfilled_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
