# Generated by Django 5.1.6 on 2025-03-24 10:25

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    MembershipPlan = apps.get_model('web', 'MembershipPlan')
    for plan in MembershipPlan.objects.all():
        plan.slug = slugify(plan.name)
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_membershipplan_usermembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('both', 'Both')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='stripe_monthly_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='stripe_yearly_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(generate_slugs),
    ]
