# Generated by Django 5.1.6 on 2025-03-26 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_waitingroom_fulfilled_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
