# Generated by Django 5.1.6 on 2025-03-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_videorequest"),
        ("web", "0044_waitingroom_fulfilled_course"),
    ]

    operations = []
