# Generated by Django 5.1.6 on 2025-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0045_auto_20250324_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplan",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Order in which to display the plan"),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
