# Generated by Django 5.1.6 on 2025-03-26 20:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0045_add_membership_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GSoCProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of your GSoC proposal", max_length=200)),
                (
                    "proposal_file",
                    models.FileField(
                        help_text="Upload your GSoC proposal in PDF format (max 10MB)",
                        upload_to="gsoc_proposals/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"]),
                            web.models.GSoCProposal.validate_gsoc_file_size,
                        ],
                    ),
                ),
                ("organization", models.CharField(help_text="GSoC organization you're applying to", max_length=200)),
                ("project", models.CharField(help_text="Specific project or idea you're proposing", max_length=200)),
                ("year", models.PositiveIntegerField(default=2025, help_text="GSoC program year")),
                ("description", models.TextField(blank=True, help_text="Brief description of your proposal")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("reviewed", "Reviewed"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, help_text="Feedback from reviewers")),
                ("file_size", models.PositiveIntegerField(editable=False, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsoc_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GSoC Proposal",
                "verbose_name_plural": "GSoC Proposals",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
