# Generated by Django 5.1.6 on 2025-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_review_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='self_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='verified_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
