# Generated by Django 5.1.6 on 2025-03-27 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("web", "0047_review_is_featured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterStatistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "counter_type",
                    models.CharField(
                        choices=[
                            ("active_users", "Active Users"),
                            ("enrollments_today", "Enrollments Today"),
                            ("courses_completed", "Courses Completed"),
                            ("quizzes_completed", "Quizzes Completed"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("enrollment", "Course Enrollment"),
                            ("quiz_completion", "Quiz Completion"),
                            ("course_completion", "Course Completion"),
                            ("challenge_completion", "Challenge Completion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("show_full_name", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
