# Generated by Django 5.1.6 on 2025-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_scheduledpost_profile_is_social_media_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={},
        ),
        migrations.RemoveField(
            model_name="badge",
            name="image",
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("perfect_attendance", "Perfect Attendance"),
                    ("participation", "Outstanding Participation"),
                    ("completion", "Course Completion"),
                    ("achievement", "Special Achievement"),
                ],
                default="perfect_attendance",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
