# Generated by Django 5.1.6 on 2025-03-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_counterstatistic_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengesubmission",
            name="student_feedback",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="challengesubmission",
            name="teacher_feedback",
            field=models.TextField(default=None),
        ),
    ]
