# Generated by Django 5.1.6 on 2025-03-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_profile_email_notifications_and_more'),
        ('web', '0048_scheduledpost_profile_is_social_media_manager'),
    ]

    operations = [
    ]
