# Generated by Django 5.1.6 on 2025-03-25 12:05

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration completes our consolidated migration.
    """

    dependencies = [
        ('web', '0001_initial'),          # The initial migration
        ('web', '0048_merged_all_migrations'),  # Our comprehensive migration
    ]

    operations = [
        # No operations needed as this is a merge migration
    ] 