# Generated by Django 5.1.6 on 2025-03-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_scheduledpost_profile_is_social_media_manager"),
        ("web", "0048_sessionattendance_self_reported_and_more"),
    ]

    operations = []
