# Generated by Django 5.1.6 on 2025-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_scheduledpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_social_media_manager",
            field=models.BooleanField(default=False),
        ),
    ]
