# Generated by Django 5.1.6 on 2025-03-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0049_session_latitude_session_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("perfect_attendance", "Perfect Attendance"),
                    ("participation", "Outstanding Participation"),
                    ("completion", "Course Completion"),
                    ("achievement", "Special Achievement"),
                    ("challenge", "Challenge Completion"),
                ],
                default="perfect_attendance",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.CharField(blank=True, help_text="URL or path to the badge image", max_length=255),
        ),
    ]
