# Generated by Django 5.1.6 on 2025-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0049_alter_badge_options_remove_badge_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("perfect_attendance", "Perfect Attendance"),
                    ("participation", "Outstanding Participation"),
                    ("completion", "Course Completion"),
                    ("achievement", "Special Achievement"),
                    ("challenge", "Challenge Completion"),
                ],
                default="perfect_attendance",
                max_length=50,
            ),
        ),
    ]
