# Generated by Django 5.1.6 on 2025-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_merge_20250329_0802'),
        ('web', '0049_session_latitude_session_longitude_and_more'),
    ]

    operations = [
    ]
