# Generated by Django 5.1.6 on 2025-03-29 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0049_challengesubmission_student_feedback_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={},
        ),
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="web.course",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="exam_type",
            field=models.CharField(
                choices=[("session", "Session Exam"), ("course", "Course Exam"), ("quiz", "Quiz")],
                default="quiz",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="web.session",
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="code_starter",
            field=models.TextField(blank=True, help_text="Starter code for coding questions"),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="diagram_data",
            field=models.JSONField(blank=True, help_text="Data for diagram questions", null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="expected_output",
            field=models.TextField(blank=True, help_text="Expected output for coding questions"),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="matching_items",
            field=models.JSONField(blank=True, help_text="Items to match", null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(default=0, help_text="Maximum attempts allowed (0 = unlimited)"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="passing_score",
            field=models.PositiveIntegerField(default=60, help_text="Minimum score to pass the exam (percentage)"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short", "Short Answer"),
                    ("fill_blank", "Fill in the Blanks"),
                    ("open_ended", "Open-Ended Questions"),
                    ("matching", "Matching Questions"),
                    ("problem_solving", "Problem-Solving Questions"),
                    ("scenario", "Scenario-Based Questions"),
                    ("diagram", "Diagram-Based Questions"),
                    ("coding", "Coding Questions"),
                ],
                default="multiple",
                max_length=20,
            ),
        ),
    ]
