# Generated by Django 5.1.6 on 2025-03-25 05:04

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):
    """
    This migration resolves any remaining model vs. database state mismatches,
    particularly around the unique_together constraint on UserBadge.
    """

    dependencies = [
        ("web", "0050_alter_userbadge_options_and_more"),
    ]

    operations = [
        # This operation tells Django that the database already has the current model state
        # without actually executing any SQL commands on the database
        SeparateDatabaseAndState(
            database_operations=[],  # No database operations needed
            state_operations=[
                # Set the unique_together constraint in the model state
                migrations.AlterUniqueTogether(
                    name="userbadge",
                    unique_together={("user", "badge")},
                ),
            ],
        ),
    ]
