# Generated by Django 5.1.6 on 2025-04-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_subject_facts"),
        ("web", "0050_profile_discord_username_profile_github_username_and_more"),
    ]

    operations = []
