# Generated by Django 5.1.6 on 2025-03-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_aichatsession_aichatmessage_learningprofile_and_more'),
        ('web', '0050_profile_discord_username_profile_github_username_and_more'),
    ]

    operations = [
    ]
