# Generated by Django 5.1.6 on 2025-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_alter_quiz_options_quiz_course_quiz_exam_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquiz",
            name="correction_status",
            field=models.CharField(
                choices=[
                    ("not_needed", "No Correction Needed"),
                    ("pending", "Correction Pending"),
                    ("in_progress", "Correction In Progress"),
                    ("completed", "Correction Completed"),
                ],
                default="not_needed",
                help_text="Status of manual correction for text questions",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(default=1, help_text="Maximum attempts allowed (0 = unlimited)"),
        ),
    ]
