# Generated by Django 5.1.6 on 2025-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_counterstatistic_alter_sessionattendance_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterstatistic",
            name="counter_type",
            field=models.CharField(
                choices=[
                    ("active_users", "Active Users"),
                    ("enrollments_today", "Enrollments Today"),
                    ("courses_completed", "Courses Completed"),
                    ("quizzes_completed", "Quizzes Completed"),
                    ("total_learners", "Total Learners"),
                    ("total_enrollments", "Total Enrollments"),
                    ("total_courses_completed", "Total Courses Completed"),
                    ("total_quizzes_taken", "Total Quizzes Taken"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
