# Generated by Django 5.1.6 on 2025-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_profile_discord_username_profile_github_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengesubmission",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
