# Generated by Django 5.1.6 on 2025-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0051_teamgoalmember_completion_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="facts",
            field=models.JSONField(blank=True, default=list, help_text="List of facts about this subject"),
        ),
    ]
