# Generated by Django 5.1.6 on 2025-03-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0051_userquiz_correction_status_alter_quiz_max_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquiz",
            name="student_feedback",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="teacher_feedback",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(default=1, help_text="Maximum attempts allowed 1"),
        ),
    ]
