# Generated by Django 5.1.6 on 2025-04-01 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_studyplan_studygoal_studysession_studyreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#4FD1C5', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='studygoal',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='studyreminder',
            old_name='sent',
            new_name='is_sent',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='studygoal',
            name='actual_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('skill', 'Skill Development'), ('exam', 'Exam Preparation'), ('project', 'Project'), ('other', 'Other')], default='academic', max_length=50),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='estimated_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='color',
            field=models.CharField(default='#4FD1C5', max_length=7),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='reminder_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='study_environment',
            field=models.CharField(choices=[('home', 'Home'), ('library', 'Library'), ('cafe', 'Cafe'), ('online', 'Online')], default='home', max_length=50),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='study_method',
            field=models.CharField(choices=[('pomodoro', 'Pomodoro Technique'), ('spaced_repetition', 'Spaced Repetition'), ('active_recall', 'Active Recall'), ('mind_mapping', 'Mind Mapping')], default='pomodoro', max_length=50),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_plans', to='web.studyplan'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='weekly_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyreminder',
            name='custom_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyreminder',
            name='repeat_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyreminder',
            name='repeat_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyreminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='actual_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='breaks_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='distractions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='focus_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studysession',
            name='mood',
            field=models.CharField(blank=True, choices=[('energetic', 'Energetic'), ('focused', 'Focused'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('neutral', 'Neutral')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='productivity_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='study_method_used',
            field=models.CharField(blank=True, choices=[('pomodoro', 'Pomodoro Technique'), ('spaced_repetition', 'Spaced Repetition'), ('active_recall', 'Active Recall'), ('mind_mapping', 'Mind Mapping')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studygoal',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='break_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='preferred_study_times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='study_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='studyreminder',
            name='reminder_type',
            field=models.CharField(choices=[('email', 'Email'), ('notification', 'In-app Notification'), ('both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.subject'),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='milestones',
            field=models.ManyToManyField(blank=True, to='web.studymilestone'),
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('book', 'Book'), ('quiz', 'Quiz'), ('worksheet', 'Worksheet'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studyplan',
            name='resources',
            field=models.ManyToManyField(blank=True, to='web.studyresource'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='resources_used',
            field=models.ManyToManyField(blank=True, to='web.studyresource'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web.studytag'),
        ),
    ]
