# Generated by Django 5.1.6 on 2025-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0052_userquiz_student_feedback_userquiz_teacher_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquiz",
            name="student_feedback",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userquiz",
            name="teacher_feedback",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
