# Generated by Django 5.1.6 on 2025-04-04 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0052_add_meme_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon_class", models.CharField(blank=True, help_text="Font Awesome icon class", max_length=50)),
            ],
            options={
                "verbose_name": "PDF Type",
                "verbose_name_plural": "PDF Types",
            },
        ),
        migrations.CreateModel(
            name="PDFSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of your document", max_length=200)),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="Upload your PDF document (max 10MB)",
                        upload_to="pdf_submissions/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"]),
                            web.models.validate_pdf_file_size,
                        ],
                    ),
                ),
                ("subject", models.CharField(help_text="Subject or department", max_length=200)),
                ("assignment", models.CharField(help_text="Assignment or topic", max_length=200)),
                ("due_date", models.DateField(blank=True, help_text="Due date (if applicable)", null=True)),
                ("description", models.TextField(blank=True, help_text="Brief description of your submission")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("reviewed", "Reviewed"),
                            ("needs_revision", "Needs Revision"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, help_text="Feedback from reviewers")),
                ("file_size", models.PositiveIntegerField(default=0, editable=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pdf_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="submissions", to="web.pdftype"
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Submission",
                "verbose_name_plural": "PDF Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
