# Generated by Django 5.1.6 on 2025-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0053_goods_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="custom_type",
            field=models.CharField(
                blank=True, help_text="Custom badge type (optional, overrides predefined types)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("perfect_attendance", "Perfect Attendance"),
                    ("participation", "Outstanding Participation"),
                    ("completion", "Course Completion"),
                    ("achievement", "Special Achievement"),
                    ("challenge", "Challenge Completion"),
                ],
                default="perfect_attendance",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Upload an image for the badge (200x200 recommended)", upload_to="badge_images/"
            ),
        ),
    ]
