# Generated by Django 5.1.6 on 2025-04-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0053_goods_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="webrequest",
            name="goods",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="web_requests",
                to="web.goods",
            ),
        ),
    ]
