# Generated by Django 5.1.6 on 2025-04-04 17:39

from django.db import migrations

import web.crypto_utils


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0053_goods_featured"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="featurevote",
            name="unique_ip_feature_vote",
        ),
        migrations.RemoveIndex(
            model_name="featurevote",
            name="web_feature_feature_988c48_idx",
        ),
        migrations.AlterField(
            model_name="donation",
            name="email",
            field=web.crypto_utils.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="featurevote",
            name="ip_address",
            field=web.crypto_utils.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="peermessage",
            name="content",
            field=web.crypto_utils.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=web.crypto_utils.EncryptedTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="discord_username",
            field=web.crypto_utils.EncryptedCharField(
                blank=True, help_text="Your Discord username (e.g., User#1234)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="expertise",
            field=web.crypto_utils.EncryptedCharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github_username",
            field=web.crypto_utils.EncryptedCharField(
                blank=True, help_text="Your GitHub username (without @)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slack_username",
            field=web.crypto_utils.EncryptedCharField(blank=True, help_text="Your Slack username", max_length=50),
        ),
        migrations.AlterField(
            model_name="webrequest",
            name="ip_address",
            field=web.crypto_utils.EncryptedCharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="webrequest",
            name="user",
            field=web.crypto_utils.EncryptedCharField(blank=True, default="", max_length=150),
        ),
    ]
