# Generated by Django 5.1.6 on 2025-04-15 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0054_chapter_chapterapplication_chapterevent_and_more"),
    ]

    operations = []
