# Generated by Django 5.1.6 on 2025-04-15 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0057_alter_educationalvideo_uploader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon_class", models.CharField(blank=True, help_text="Font Awesome icon class", max_length=50)),
                (
                    "allowed_file_types",
                    models.CharField(
                        default="pdf",
                        help_text="Comma-separated list of allowed file extensions (e.g., 'pdf,doc,docx')",
                        max_length=200,
                    ),
                ),
                ("max_file_size_mb", models.PositiveIntegerField(default=10, help_text="Maximum file size in MB")),
            ],
            options={
                "verbose_name": "Work Type",
                "verbose_name_plural": "Work Types",
            },
        ),
        migrations.CreateModel(
            name="WorkSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of your document", max_length=200)),
                (
                    "work_file",
                    models.FileField(
                        help_text="Upload your document (file type and size restrictions apply)",
                        upload_to="work_submissions/",
                    ),
                ),
                ("subject", models.CharField(help_text="Subject or department", max_length=200)),
                ("assignment", models.CharField(help_text="Assignment or topic", max_length=200)),
                ("due_date", models.DateField(blank=True, help_text="Due date (if applicable)", null=True)),
                ("description", models.TextField(blank=True, help_text="Brief description of your submission")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("reviewed", "Reviewed"),
                            ("needs_revision", "Needs Revision"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, help_text="Feedback from reviewers")),
                ("file_size", models.PositiveIntegerField(default=0, editable=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="submissions", to="web.worktype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Submission",
                "verbose_name_plural": "Work Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
