# Generated by Django 5.1.6 on 2025-04-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_forumtopic_github_issue_url_and_more'),
        ('web', '0058_question_choice_response_survey_question_survey'),
    ]

    operations = [
    ]
