# Generated by Django 5.1.6 on 2025-04-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0058_forumtopic_github_issue_url_and_more"),
        ("web", "0058_profile_email_bounce_count_profile_email_click_count_and_more"),
    ]

    operations = []
