# Generated by Django 5.1.6 on 2025-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0058_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="AI_auto_correction",
            field=models.BooleanField(
                default=False, help_text="If enabled, AI will automatically attempt to correct open-ended questions"
            ),
        ),
    ]
