# Generated by Django 5.1.6 on 2025-04-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0059_quiz_ai_auto_correction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["created_at"]},
        ),
    ]
