# Generated by Django 5.1.6 on 2025-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_alter_quiz_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="code_starter",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="diagram_data",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="expected_output",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="matching_items",
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="reference_answer",
            field=models.TextField(
                blank=True, help_text="Reference answer for the questions, important when AI-auto correction", null=True
            ),
        ),
    ]
