# Generated by Django 5.1.6 on 2025-04-25 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_question_choice_response_survey_question_survey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="score",
        ),
        migrations.AddField(
            model_name="challengesubmission",
            name="student_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="challengesubmission",
            name="teacher_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quiz",
            name="AI_auto_correction",
            field=models.BooleanField(
                default=False, help_text="If enabled, AI will automatically attempt to correct open-ended questions"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="web.course",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="exam_type",
            field=models.CharField(
                choices=[("session", "Session Exam"), ("course", "Course Exam"), ("quiz", "Quiz")],
                default="quiz",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="web.session",
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="reference_answer",
            field=models.TextField(
                blank=True, help_text="Reference answer for the questions, important when AI-auto correction", null=True
            ),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="correction_status",
            field=models.CharField(
                choices=[
                    ("not_needed", "No Correction Needed"),
                    ("pending", "Correction Pending"),
                    ("in_progress", "Correction In Progress"),
                    ("completed", "Correction Completed"),
                ],
                default="not_needed",
                help_text="Status of manual correction for text questions",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="student_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userquiz",
            name="teacher_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="educationalvideo",
            name="description",
            field=models.TextField(blank=True, help_text="Optional - describe what viewers will learn from this video"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(default=1, help_text="Maximum attempts allowed"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="passing_score",
            field=models.PositiveIntegerField(default=60, help_text="Minimum score to pass the exam (percentage)"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short", "Short Answer"),
                    ("fill_blank", "Fill in the Blanks"),
                    ("open_ended", "Open-Ended Questions"),
                    ("matching", "Matching Questions"),
                    ("problem_solving", "Problem-Solving Questions"),
                    ("scenario", "Scenario-Based Questions"),
                    ("diagram", "Diagram-Based Questions"),
                    ("coding", "Coding Questions"),
                ],
                default="multiple",
                max_length=20,
            ),
        ),
    ]
