# Generated by Django 5.1.6 on 2025-04-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_alter_educationalvideo_description_videorequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, help_text='Educational video that fulfills this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilling_requests', to='web.educationalvideo'),
        ),
    ]
