# Generated by Django 5.1.6 on 2025-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_alter_quiz_options_remove_userquiz_max_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="enable_copy_past_and_text_selection",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the student will be able to copy/past and select text inside the exam.",
            ),
        ),
    ]
