# Generated by Django 5.1.6 on 2025-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_alter_educationalvideo_description_videorequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalvideo",
            name="video_id",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Auto-generated unique video identifier.",
                max_length=12,
                unique=True,
            ),
        ),
    ]
