# Generated by Django 5.1.6 on 2025-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_remove_quizquestion_code_starter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquiz",
            name="max_score",
        ),
        migrations.AlterField(
            model_name="userquiz",
            name="score",
            field=models.FloatField(default=0.0),
        ),
    ]
