# Generated by Django 5.1.6 on 2025-10-24 19:19

import django.db.models.deletion
import web.encryption_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_update_waitingroom_for_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEncryption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "encrypted_first_name",
                    web.encryption_fields.EncryptedTextField(blank=True, help_text="Encrypted first name"),
                ),
                (
                    "encrypted_last_name",
                    web.encryption_fields.EncryptedTextField(blank=True, help_text="Encrypted last name"),
                ),
                (
                    "encrypted_email",
                    web.encryption_fields.EncryptedTextField(blank=True, help_text="Encrypted email address"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Encryption",
                "verbose_name_plural": "User Encryptions",
            },
        ),
    ]
