# Generated by Django 5.1.6 on 2025-10-05 06:45

import encrypted_model_fields.fields
import web.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_update_waitingroom_for_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
        migrations.AlterField(
            model_name='featurevote',
            name='ip_address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=web.encryption.CustomEncryptedJSONField(blank=True, help_text='Structured shipping details', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discord_username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Your Discord username (e.g., User#1234)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Your GitHub username (without @)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slack_username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Your Slack username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_account_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='webrequest',
            name='ip_address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
