# Generated by Django 5.1.6 on 2025-10-11 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_update_waitingroom_for_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Lobby', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the lobby')),
                ('max_users', models.IntegerField(default=100, help_text='Maximum number of users allowed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the lobby is currently active')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the lobby is public or private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtual Lobby',
                'verbose_name_plural': 'Virtual Lobbies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LobbyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0, help_text='X coordinate in the virtual space')),
                ('position_y', models.FloatField(default=0.0, help_text='Y coordinate in the virtual space')),
                ('avatar_url', models.URLField(blank=True, help_text='Custom avatar URL')),
                ('display_name', models.CharField(blank=True, help_text='Display name in the lobby', max_length=50)),
                ('avatar_color', models.CharField(default='#3B82F6', help_text='Avatar color in hex format', max_length=7)),
                ('is_online', models.BooleanField(default=True, help_text='Whether the user is currently online')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined the lobby')),
                ('is_muted', models.BooleanField(default=False, help_text='Whether the user is muted')),
                ('allow_direct_messages', models.BooleanField(default=True, help_text='Allow direct messages from other users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_participations', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='web.virtuallobby')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'lobby')},
            },
        ),
    ]
