# Generated by Django 5.1.6 on 2025-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_remove_userquiz_max_score_alter_userquiz_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquiz",
            name="score",
        ),
    ]
