# Generated by Django 5.1.6 on 2025-10-05 17:52

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0063_add_encryption_to_personal_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="encrypted_email",
            field=encrypted_model_fields.fields.EncryptedEmailField(
                blank=True, help_text="Encrypted email (synced from User model)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Encrypted first name (synced from User model)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Encrypted last name (synced from User model)"
            ),
        ),
    ]
