all:
  hosts:
    education_server:
      ansible_host: 45.76.4.171
      ansible_user: root
      ansible_ssh_pass: "Jm-7Yt?(,KLQ!r$Q"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    # Project settings (matching actual server location)
    project_name: education-website
    project_user: root
    project_dir: "/home/root/education-website"
    app_port: 8000
    
    # Database settings (matching setup.sh)
    db_name: education_website
    db_user: root
    
    # Domain settings (matching setup.sh - empty for IP-only)
    domain_name: "45.76.4.171"
    enable_https: false
    
    # Django settings
    django_settings_module: web.settings
    python_version: "3.11"
    
    # Redis settings
    redis_port: 6379
    redis_host: localhost 