all:
  children:
    development:
      hosts:
        test-server:
          ansible_host: 45.76.4.171
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/education_website_key
          ansible_host_key_checking: false
    production:
      hosts:
        prod-server:
          ansible_host: your-production-ip
          ansible_user: deploy