---
- hosts: production
  become: yes
  vars:
    project_name: "{{ lookup('env', 'PROJECT_NAME') | default('education-website', true) }}"

  tasks:
    - name: Reboot the server
      reboot:
        msg: "Rebooting server for maintenance"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Wait for server to come back online
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

    - name: Check if services are running after reboot
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - "{{ project_name }}"
        - postgresql

    - name: Display service status
      command: "systemctl status {{ item }} --no-pager -l"
      loop:
        - nginx
        - "{{ project_name }}"
        - postgresql
      register: service_status
      ignore_errors: yes

    - name: Show service status results
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ service_status.results }}"
      when: item.stdout_lines is defined