# Secrets file - extracted from existing working setup
# Based on setup.sh and .env configuration

# Django Configuration (from .env)
django_secret_key: "5ezrkqK2lhifqBRt9f8_dZhFQF_f5ipSQDV8Vzv9Dek="

# Database Configuration (generated in setup.sh)
database_password: "secure_db_password_123"

# Redis Configuration (for Django Channels)
redis_password: "secure_redis_password_123"

# Email Configuration (from .env)
email_from: "admin@example.com"
sendgrid_api_key: "your-sendgrid-api-key"
sendgrid_password: "your-sendgrid-password"

# Stripe Configuration (from .env)
stripe_publishable_key: "your-stripe-publishable-key"
stripe_secret_key: "your-stripe-secret-key"
stripe_webhook_secret: "your-stripe-webhook-secret"

# Admin URL (from .env)
admin_url: "a-dmin-url123"

# Message Encryption Key (from .env)
message_encryption_key: "5ezrkqK2lhifqBRt9f8_dZhFQF_f5ipSQDV8Vzv9Dek="

# Slack Configuration (from .env)
slack_webhook_url: "your-slack-webhook-url"

# Twitter Configuration (from .env)
twitter_api_key: "your_api_key_here"
twitter_api_secret_key: "your_api_secret_here"
twitter_access_token: "your_access_token_here"
twitter_access_token_secret: "your_access_token_secret_here"

# Google Cloud Storage Configuration (from .env)
gs_bucket_name: "your-bucket-name"
gs_project_id: "your-project-id"
service_account_file: "your-service-account-file-path"

# GitHub Token (from .env)
github_token: "your-github-token"
