# Generated by Django 5.1.6 on 2025-03-14 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressrecord',
            options={'ordering': ['subject', 'topic']},
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='questions_attempted',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='questions_correct',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='study_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='milestones',
        ),
        migrations.AddField(
            model_name='interaction',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='include_examples',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='include_visuals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='response_length',
            field=models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('comprehensive', 'Comprehensive')], default='detailed', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('gpt', 'OpenAI GPT'), ('claude', 'Anthropic Claude'), ('demo', 'Demo Mode')], default='demo', max_length=50),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='mastery_level',
            field=models.IntegerField(choices=[(1, 'Novice'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='difficulty_preference',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('adaptive', 'Adaptive')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic')], default='visual', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
