# Generated by Django 5.1.6 on 2025-03-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_progressrecord_options_and_more'),
        ('ai', '0002_chatsession_message'),
    ]

    operations = [
    ]
