# Generated by Django 5.1.6 on 2025-03-29 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_merge_20250322_0656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='progressrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='feedback_rating',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='progressrecord',
            old_name='updated_at',
            new_name='last_interaction',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='feedback_comment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='order',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='include_examples',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='include_visuals',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='content',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='subject',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='ai_provider',
            field=models.CharField(default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='mastery_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='difficulty_preference',
            field=models.CharField(default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_style',
            field=models.CharField(default='visual', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='response_length',
            field=models.CharField(default='detailed', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
