# Generated by Django 5.1.6 on 2025-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_achievement_subject_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='completed_hours',
            field=models.IntegerField(default=0),
        ),
    ]
