name: Docker Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - 'requirements.txt'
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - 'requirements.txt'
      - '**.py'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: education-website:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start Docker container
        run: |
          docker run -d -p 8000:8000 --name education-app education-website:test
          # Wait for the container to start up
          sleep 10
          docker ps

      - name: Check container logs
        run: docker logs education-app

      - name: Test HTTP endpoint
        run: |
          # Check if the website is responding
          curl -s --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8000/en/ -o /dev/null -w "%{http_code}\n" | grep -q "200" && echo "Website is up!" || (echo "Website is down!" && exit 1)

      - name: Stop Docker container
        if: always()
        run: docker stop education-app
