name: Tests

on:
  push:
  pull_request:

# Add permissions needed for commenting on PRs
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python3.10.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
        cache: 'pip'

    - name: Run pre-commit hooks
      id: pre-commit
      run: |
        pip install pre-commit black isort flake8 djlint
        #pre-commit autoupdate
        pre-commit install
        pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python3.10.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
        cache: 'pip'

    - name: Run tests
      run: |
        cp .env.sample .env
        python -m pip install --upgrade pip wheel setuptools
        pip install -v -r requirements.txt
        python manage.py test

    # - name: Run tests with coverage
    #   run: |
    #     pytest -v --cov=web --cov-report=xml

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python3.10.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
        cache: 'pip'

    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check
