# Generated by Django 5.1.6 on 2025-03-25 04:50

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration merges the two previously merged migrations:
    - 0035_merged_badge_challenge_migrations (which merged badge, challenge, etc. migrations)
    - 0044_merged_membership_migrations (which merged membership plan migrations)
    """

    dependencies = [
        ("web", "0035_merged_badge_challenge_migrations"),
        ("web", "0044_merged_membership_migrations"),
    ]

    operations = [
        # No operations needed as this is just a merge of two migration branches
    ] 